pipeline {
    agent any

    tools {
        maven 'Maven3'
        jdk 'JDK17'
    }

    stages {
        stage('Clone and Build') {
            steps {
                git branch: 'feature/pipeline-jenkins',
                url: 'https://github.com/panoramac/LibraryManagement_ProjetDevops.git'

                dir('library-management') {
                    bat 'mvn clean compile test package'
                }
            }
            post {
                success {
                    archiveArtifacts 'library-management/**/target/*.war'
                    junit 'library-management/**/target/surefire-reports/*.xml'
                }
            }
        }
    }

    post {
        always {
            echo "Build finished: ${currentBuild.currentResult}"
        }
    }
}